server:
  port: 8088

spring:
  application:
    name: yangsx-user-center
  datasource:
    url: jdbc:mysql://47.98.113.103:3306/user_center
    hikari:
      username: root
      password: abc.123
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 47.98.113.103:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
